version: "3"

services:
  jupyter:
    image: tensorflow/tensorflow:latest-gpu-jupyter
    container_name: jupyter
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=easy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
